### ISSUE TITLE
restore is not the inverse of dump

### ISSUE THREAD

**Issue by Mulugruntz** [edgedb/edgedb#2433]
- EdgeDB Version: Docker image: edgedb/edgedb:1-beta1
- OS Version:

Steps to Reproduce:

1. `edgedb dump backup --all --format=dir`
2. `edgedb restore -v --allow-non-empty --all backup`

Result:
```
edgedb error: error applying init file "backup/init.edgeql": failed statement "# DESCRIBE ROLES\nCREATE SUPERUSER ROLE `myuser` { SET password_hash := \'SCRAM-SHA-256$4096:xxxxxxxxxxx=\'};": ERROR: SchemaError: role 'myuser' is already present in the schema
```

I would expect that if I put `--allow-non-empty`, especially with `--all`, I would be allowed to do such a thing.
Is it as intended?

I feel like there should be a way to cleanly "start fresh from a full backup".

**Comment by Mulugruntz** [comment]
By the way, if I do:
```
$> edgedb drop-role myuser
$> edgedb restore -v --allow-non-empty --all backup
edgedb error: ERROR: AuthenticationError: authentication failed
```

Hmmm.... maybe I would need to use the `edgedb` role for that, instead? Not sure how to do it...

**Comment by elprans** [comment]
>  Is it as intended?

Generally yes.  Unlike Postgres, EdgeDB will not let you restore schema objects that already exist in the target database or instance.

> Hmmm.... maybe I would need to use the `edgedb` role for that, instead? Not sure how to do it...

The `edgedb` role is the default, so you can either omit `-e EDGEDB_USER` or specify `-e EDGEDB_USER=edgedb` explicitly when starting up a fresh server in a container.

That said, it seems we need to consider emitting `ROLE` objects with `IF NOT EXISTS` in dumps.

**Comment by Mulugruntz** [comment]
yes, agreed with the last statement :-).

In my dump scripts, I'll try to amend the file to put `IF NOT EXISTS` in the meantime.

**Comment by Mulugruntz** [comment]
Erm... there's no `IF NOT EXISTS` statement to the role creation, is there?
https://www.edgedb.com/docs/edgeql/admin/roles#create-role

**Comment by Mulugruntz** [comment]
After commenting out the `CREATE SUPERUSER ROLE`, I still have an error message
```
edgedb error: restoring database "edgedb": Error initiating restore protocol: ERROR: SchemaDefinitionError: specified migration parent is not the most recent migration, expected 'm14zgmivx7oosifsy4oht376mmbmlb3bhwue5dbj7xj464uwqogjvq'
```

What would you advise?

**Comment by elprans** [comment]
> What would you advise?

Use the `edgedb` role.

**Comment by Mulugruntz** [comment]
With the `edgedb` role.
```
edgedb error: ERROR: AuthenticationError: invalid SCRAM verifier for user 'edgedb'
```

**Comment by elprans** [comment]
You need to use `edgedb` when you are starting the server container on a fresh data volume for the first time to initialize it with the supplied password.  Switching the role afterwards does not reset its password.

**Comment by Mulugruntz** [comment]
Not sure when I can do that.
Because my docker-compose will start both services and will create everything.

Maybe I misunderstand something, but as of now, dump/restore doesn't seem usable, does it?
I haven't managed to make it work, so far.

I was expecting something like `pg_dump`. https://www.postgresql.org/docs/13/app-pgdump.html
`pg_dump -Fc > filename` and `pg_restore filename`

I think I'm gonna try a different strategy:
Backup:

1. stop the server
2. tar.gz the Filesystem, storing it on host.
3. start the server

Restore:
1. stop the server
2. mount a volume with the tar.gz, extract the tar.gz
3. start the server

**Comment by elprans** [comment]
> Maybe I misunderstand something, but as of now, dump/restore doesn't seem usable, does it?

The issue is that you are using a custom `ROLE` instead of the default (`edgedb`).  When you start a docker container for the first time on an empty data volume, it configures the authentication for that data volume (with values from `EDGEDB_USER` and `EDGEDB_PASSWORD`).  If you've used a non-default role, and then attempted to restore a full backup it'd crash with the "role already present" error.  

(we'll make a change to teach the dump to be tolerant of overlapping roles in beta 2)

The solution for your issue is as follows: 

1. Make a dump from the original data volume
2. Stop the server.
3. Make a new, empty directory for the data volume.
4. Remove `EDGEDB_USER` from your `docker-compose.yml`.
5. Start the container.
6. Restore the dump.

**Comment by elprans** [comment]
Alternatively, don't use `--all` and restore databases one by one.

**Comment by elprans** [comment]
@Mulugruntz, can you share your `docker-compose.yml` please?  Also, did you try the steps I outlined above?

**Comment by Mulugruntz** [comment]
I tried to do what you advised me (and some other stuff as well).
But I wasn't sure about steps 3 & 4...

And to script the dump/restore, without destroying the whole environment, from my understanding, that doesn't seem practical?

**docker-compose.yml**
<details>

```yaml
version: '3'
services:
  tempbot:
    container_name: tempbot
    build: .
    ports:
      - "4242:8000" # The webserver
    volumes:
    - ./logs:/var/log
    links:
    - edgedb
    depends_on:
    - edgedb
  edgedb:
    container_name: edgedb
    image: edgedb/edgedb:1-beta1
    environment:
      - EDGEDB_USER=user
      - EDGEDB_PASSWORD=password
#      - EDGEDB_DEBUG_PGSERVER=1
    ports:
    - "5656:5656" # EdgeQL over binary protocol
    - "8889:8889" # EdgeQL over HTTP
    - "8888:8888" # GraphQL over HTTP
    volumes:
    - edgedb-db:/var/lib/edgedb/data
volumes:
  edgedb-db: {}
```

</details>
