### ISSUE TITLE
ConnectionResetError docker

### ISSUE THREAD

**Issue by Forbidden-A** [edgedb/edgedb#2973]
- EdgeDB Version: `1.0-beta.4+dev6013.d2021092410.gab26440d9.cv202109220000`
- OS Version: `x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit` (Docker)

I have a docker-compose file:

```yml
version: "3.8"

services:
  bot:
    build: "."
    depends_on:
      - "db"
    env_file: "./.env"
    links:
      - "db"

  db:
    image: "edgedb/edgedb:nightly"
    env_file: "./.env"
    environment:
      EDGEDB_PASSWORD: "${EDGEDB_PASSWORD}"
      EDGEDB_GENERATE_SELF_SIGNED_CERT: 1
    volumes:
      - ".edgedb:/var/lib/edgedb/data"
    ports:
      - "5656:5656"
      - "8888:8888"
```
when I first build and run, python refuses to connect to Database, it errors with the following

```
edgedb.errors.ClientConnectionFailedError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)
	After 26 attempts in 2.7 sec
```

when I restart however, I get an error from the database container:  

```
---- Exception occurred ----

1. ConnectionResetError:

---- Traceback ----

    edb/server/protocol/protocol.pyx, line 288, in _start_tls

    uvloop/loop.pyx, line 1624, in start_tls

    uvloop/loop.pyx, line 1617, in uvloop.loop.Loop.start_tls

    uvloop/sslproto.pyx, line 517, in uvloop.loop.SSLProtocol._on_handshake_complete


ConnectionResetError:
ERROR 1 2021-09-27T15:11:58.744 asyncio: Task exception was never retrieved
future: <Task finished name='Task-36' coro=<<coroutine without __name__>()> exception=ConnectionResetError()>
```
I've no idea how TLS works or how to set it up, I was just trying to make a simple discord bot. I've no idea if its something I did wrong, please go easy on me 😅
