### ISSUE TITLE
Documentation on Spinning up a local containerized environment

### ISSUE THREAD

**Issue by kwsorensen** [edgedb/edgedb#4170]
I am interested in exploring EdgeDB, however I am not interested installing dependencies in my local machine outside of containers/VMs. 

Typically, when exploring something new I stand up a container (e.g. a postgres or a redis container) so that it is isolated to that environment and provides an easy reset if I screw something up. This workflow has worked great for me and other developers and would be great to have as a step in the journey for people to adopt edgedb.

**Comment by Sikarii** [comment]
Hey, using it with Docker should be fairly easy, heres an example Docker Compose file **for development**:
```yaml
version: "3.9"

services:
  edgedb:
    image: edgedb/edgedb:2.0
    restart: unless-stopped
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "./dbschema:/dbschema"
      - "./data/edgedb:/var/lib/edgedb/data"
    ports:
      - "5656:5656"
```

Spin this up and run `edgedb instance link` in your project's directory and follow the prompts.
Note that the first boot of the container takes some time, you can observe logs to see its progress.

In production you should NOT use `EDGEDB_SERVER_SECURITY=insecure_dev_mode`.
