### ISSUE TITLE
Not working with docker compose + backend dsn

### ISSUE THREAD

**Issue by scottmas** [edgedb/edgedb#4457]
The following docker-compose.yaml file does not successfully bootstrap. When each service is started indenpendently, it works fine however. It could be something I'm doing or maybe some weird internals of docker networking that EdgeDB hasn't accounted for? Thanks!

```yaml
version: "3"
services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev-db
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
  edgedb:
    image: edgedb/edgedb
    depends_on:
      - postgres
    environment:
      EDGEDB_SERVER_PASSWORD: password
      EDGEDB_SERVER_DATABSE: edgedb_test
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_SERVER_BACKEND_DSN: postgres://postgres:password@localhost:5432/dev-db
    volumes:
      - ./dbschema:/dbschema
    ports:
      - 5656:5656
```

**Comment by Syzuna** [comment]
The DSN is wrong.
localhost in this case means inside the same container as edgedb. (every container more or less is its own Virtual PC/Server)
you would need to change localhost for the name of the container and I also think you dont need the /dev-db here bcs you try to connect to the whole instance not just 1 single db

**Comment by scottmas** [comment]
Thank you! The corrected docker-compose.yaml is below.

As a note, it took fully 2 minutes for my edgedb instance to be available for connection. That seems like a reaaaaal long time, almost making it completely unviable to use docker-compose in my dev setup. 

Corrected docker-compose.yaml below:
```yaml
version: "3"
services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev-db
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
  edgedb:
    image: edgedb/edgedb
    depends_on:
      - postgres
    environment:
      EDGEDB_SERVER_PASSWORD: password
      EDGEDB_SERVER_DATABSE: edgedb_test
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_SERVER_BACKEND_DSN: postgres://postgres:password@postgres:5432
    volumes:
      - ./dbschema:/dbschema
    ports:
      - 5656:5656
```
