### ISSUE TITLE
Extremely slow docker start

### ISSUE THREAD

**Issue by scottmas** [edgedb/edgedb#4468]
I consistently get extremely slow startups with docker-compose on my mac, roughly 1 minute and 30 seconds. My docker compose is as follows:

```yaml
version: "3"
services:
  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev-db
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
  edgedb:
    image: edgedb/edgedb
    depends_on:
      - postgres
    environment:
      EDGEDB_SERVER_PASSWORD: password
      EDGEDB_SERVER_DATABSE: edgedb_test
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_SERVER_BACKEND_DSN: postgres://postgres:password@postgres:5432
    volumes:
      - ./dbschema:/dbschema
    ports:
      - 5656:5656
```
And my `docker-compose up` output is as follows. The docker container seems to be booting up several times before I can finally accept connections. 

```bash
edgedb_1    | Bootstrapping EdgeDB instance on remote Postgres cluster...
postgres_1  | 
postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  | 
postgres_1  | 2022-10-02 20:03:15.674 UTC [1] LOG:  starting PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
postgres_1  | 2022-10-02 20:03:15.674 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2022-10-02 20:03:15.674 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2022-10-02 20:03:15.681 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2022-10-02 20:03:15.716 UTC [28] LOG:  database system was interrupted; last known up at 2022-09-30 08:01:53 UTC
postgres_1  | 2022-10-02 20:03:30.359 UTC [28] LOG:  database system was not properly shut down; automatic recovery in progress
postgres_1  | 2022-10-02 20:03:30.515 UTC [28] LOG:  redo starts at 0/3047F80
postgres_1  | 2022-10-02 20:03:30.531 UTC [28] LOG:  invalid record length at 0/3050CC8: wanted 24, got 0
postgres_1  | 2022-10-02 20:03:30.531 UTC [28] LOG:  redo done at 0/30507C0 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.01 s
postgres_1  | 2022-10-02 20:03:30.589 UTC [1] LOG:  database system is ready to accept connections
edgedb_1    | INFO 107 2022-10-02T20:03:34.813 edb.server: starting EdgeDB server 2.1+c600476, built on 2022-08-05T21:26Z from revision dabe13885 (2022-08-05T02:01Z) for x86_64-unknown-linux-gnu
edgedb_1    | INFO 107 2022-10-02T20:03:34.815 edb.server: instance name: '_unknown'
edgedb_1    | INFO 107 2022-10-02T20:03:41.194 edb.server: Detected 97 backend connections available.
edgedb_1    | INFO 107 2022-10-02T20:03:46.665 edb.server: introspecting extensions for database '__edgedbsys__'
edgedb_1    | INFO 107 2022-10-02T20:03:46.668 edb.server: introspecting extensions for database 'edgedb'
edgedb_1    | INFO 107 2022-10-02T20:03:47.602 edb.server: Connection established to backend database: __edgedbsys__
edgedb_1    | INFO 107 2022-10-02T20:03:47.946 edb.server: Connection established to backend database: edgedb
edgedb_1    | INFO 107 2022-10-02T20:03:48.028 edb.server: generating JOSE key pair in "/tmp/tmp.4dbER9Sfur/w448oyh6/edbjwskeys.pem"
edgedb_1    | INFO 107 2022-10-02T20:03:48.139 edb.server: generating JOSE key pair in "/tmp/tmp.4dbER9Sfur/w448oyh6/edbjwekeys.pem"
edgedb_1    | INFO 107 2022-10-02T20:03:58.728 edb.server: started 1 compiler worker process
edgedb_1    | INFO 107 2022-10-02T20:03:58.737 edb.server: Serving on 127.0.0.1:33049
edgedb_1    | INFO 107 2022-10-02T20:03:58.739 edb.server: Serving admin on /tmp/tmp.4dbER9Sfur/.s.EDGEDB.admin.33049
edgedb_1    | [2022-10-02T20:04:00Z WARN  edgedb::version_check] Newer version of edgedb tool exists 2.0.5+f78cf34 (current 2.0.4+c7a8cb4)
edgedb_1    | INFO 107 2022-10-02T20:04:00.584 edb.server: introspecting database 'edgedb'
edgedb_1    | Connecting to an EdgeDB instance at 127.0.0.1:33049...
edgedb_1    | [2022-10-02T20:04:03Z WARN  edgedb::version_check] Newer version of edgedb tool exists 2.0.5+f78cf34 (current 2.0.4+c7a8cb4)
edgedb_1    | Everything is up to date. Revision m1wq5due6jnmotvs3thfjy3conjyxxmbmw7c6enwrg27gcw2avryla
edgedb_1    | INFO 107 2022-10-02T20:04:03.699 edb.server: Received signal: Signals.SIGTERM.
edgedb_1    | INFO 107 2022-10-02T20:04:03.700 edb.server: Shutting down.
edgedb_1    | INFO 1 2022-10-02T20:04:15.617 edb.server: starting EdgeDB server 2.1+c600476, built on 2022-08-05T21:26Z from revision dabe13885 (2022-08-05T02:01Z) for x86_64-unknown-linux-gnu
edgedb_1    | INFO 1 2022-10-02T20:04:15.619 edb.server: instance name: '_unknown'
edgedb_1    | INFO 1 2022-10-02T20:04:21.658 edb.server: Detected 97 backend connections available.
edgedb_1    | INFO 1 2022-10-02T20:04:26.103 edb.server: introspecting extensions for database '__edgedbsys__'
edgedb_1    | INFO 1 2022-10-02T20:04:26.105 edb.server: introspecting extensions for database 'edgedb'
edgedb_1    | INFO 1 2022-10-02T20:04:26.960 edb.server: Connection established to backend database: edgedb
edgedb_1    | INFO 1 2022-10-02T20:04:26.973 edb.server: Connection established to backend database: __edgedbsys__
edgedb_1    | INFO 1 2022-10-02T20:04:26.987 edb.server: generating JOSE key pair in "/run/edgedb/6liv8ybj/edbjwskeys.pem"
edgedb_1    | INFO 1 2022-10-02T20:04:27.095 edb.server: generating JOSE key pair in "/run/edgedb/6liv8ybj/edbjwekeys.pem"
edgedb_1    | INFO 1 2022-10-02T20:04:37.905 edb.server: started 5 compiler worker processes
edgedb_1    | INFO 1 2022-10-02T20:04:37.921 edb.server: Serving on {0.0.0.0, ::}:5656
edgedb_1    | INFO 1 2022-10-02T20:04:37.924 edb.server: Serving admin on /run/edgedb/.s.EDGEDB.admin.5656
edgedb_1    | INFO 1 2022-10-02T20:04:46.403 edb.server: introspecting database 'edgedb'
```
