### ISSUE TITLE
ClientError: AuthenticationError: authentication failed

### ISSUE THREAD

**Issue by alexgorbatchev** [edgedb/edgedb#5137]
- EdgeDB Version: `2.12`
- EdgeDB CLI Version: `2.3.1+ef99779`
- OS Version: `Linux 21a2ac190a2d 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 GNU/Linux`

I'm attempting to use EdgeDB UI and find myself unable to get it to work:

1. If I don't specify `EDGEDB_SERVER_USER` and `EDGEDB_SERVER_PASSWORD`
  a. I can access EdgeDB server via CLI with `--dsn=edgedb://localhost:5656 --tls-security=insecure`
  b. I can't login into EdgeDB UI due to `Error: Invalid credentials`
2. If I specify `EDGEDB_SERVER_USER` and `EDGEDB_SERVER_PASSWORD`
  a. I can't access EdgeDB server via CLI with `--dsn=edgedb://admin:password@localhost:5656 --tls-security=insecure` due to `ClientError: AuthenticationError: authentication failed`
  b. I can't login into EdgeDB UI due to `Error: Invalid credentials`

Basically, I can't use the UI at all because if I understand correctly it currently doesn't support `Trust` auth and I'm unable to access the server AND the UI with `SCRAM` auth method. What am I doing wrong?

Here are my ENV variables:

```yaml
- name: EDGEDB_SERVER_SECURITY
  value: insecure_dev_mode
- name: EDGEDB_DOCKER_LOG_LEVEL
  value: trace
- name: EDGEDB_PORT
  value: "5656"
- name: EDGEDB_SERVER_BIND_ADDRESS
  value: "0.0.0.0"
- name: EDGEDB_SERVER_ADMIN_UI
  value: enabled
- name: EDGEDB_SERVER_USER
  value: admin
- name: EDGEDB_SERVER_PASSWORD
  value: password
```

Steps to reproduce for UI:

1. open `https://localhost:5656/ui/_login`
3. use `admin` and `password`
4. Receive `Error: Invalid credentials`

![image](https://user-images.githubusercontent.com/65633/223500699-a57c25c5-e0e0-483b-8db5-0c3aff19bc5a.png)
