### ISSUE TITLE
Unable to Sync Data from Edgedb to Snowflake via Fivetran

### ISSUE THREAD

**Issue by rajeshdhanda** [edgedb/edgedb#5965]
- EdgeDB Version: 3.2
- EdgeDB CLI Version: EdgeDB CLI 3.4.0+160d07d

### Current Behavior

I'm experiencing an issue while trying to synchronize data from Edgedb (version 3.2) to Snowflake using Fivetran. 
Here are the steps I've taken and the error I'm encountering:

1. I've connected to Edgedb instance deployed on GKE. Backend is a Cloud SQL PostgreSQL instance with version 15.
2. I migrated the data from an Edgedb version 2.7 instance (with PostgreSQL 14 backend) to the Edgedb version 3.2 instance (with PostgreSQL 15 backend).
3. I used the psql CLI to connect to the Edgedb instance and execute read-only SQL queries successfully:
```
psql -h host -p 5656 -U postgres -d dbname
```
4. I want to synchronize this data to Snowflake using Fivetran.

### Error Message

Fivetran is displaying an error message that reads: `Unable to determine the availability of XMIN extensions` 

### Steps to Reproduce

1. Deploy Edgedb version 3.2 on GKE with Cloud SQL PostgreSQL instance version 15 as the backend.
3. Migrate data from an Edgedb version 2.7 instance to the Edgedb version 3.2 instance.
4. Set up Fivetran to synchronize data from Edgedb to Snowflake.
5. Observe the `Unable to determine the availability of XMIN extensions` error..

## Additional Context

I also attempted changing the PostgreSQL version to 14 and creating a default example database to troubleshoot the issue. However, the same error persisted.

Please let me know if there are any further details or logs I can provide to help resolve this issue.

---

**Attachments:**

<details><summary>XMIN extensions not enabled</summary>
<p>

![](https://cdn.discordapp.com/attachments/849377751370432573/1144593572130193490/image.png)

</p>
</details> 

<details><summary>Edgedb Deployment Configuration </summary>
<p>

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgedb3
  labels:
    app: edgedb3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgedb3
  template:
    metadata:
      labels:
        app: edgedb3
    spec:
      containers:

        - name: edgedb3-container
          image: edgedb/edgedb:3.2
          ports:
            - containerPort: 5656

          volumeMounts:
          - name: edgedb-secret-volume
            readOnly: true
            mountPath: "/etc/secret-volume"

          env:
            - name: EDGEDB_SERVER_INSTANCE_NAME
              value: edgedb3-server
            - name: EDGEDB_SERVER_TLS_CERT_MODE
              value: require_file
            - name: EDGEDB_SERVER_PASSWORD
              value: password
            - name: EDGEDB_SERVER_BACKEND_DSN
              value: postgresql://user:password@127.0.0.1:5432
            - name: EDGEDB_SERVER_TLS_CERT_FILE
              value: /etc/secret-volume/tls-cert
            - name: EDGEDB_SERVER_TLS_KEY_FILE
              value: /etc/secret-volume/tls-key
            - name: EDGEDB_SERVER_USER
              value: postgres
            - name: EDGEDB_SERVER_ADMIN_UI
              value: enabled
            - name: EDGEDB_SERVER_BINARY_ENDPOINT_SECURITY
              value: optional

        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0  
          args:
            - "--port=5432"
            - "gcpProject:zone:instance"
            - "--credentials-file=/secrets/cloudsql/credentials.json"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true

      volumes:

        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials

        - name: edgedb-secret-volume
          secret:
            secretName: tls-secret
```

</p>
</details>
