### ISSUE TITLE
Graphql and docker

### ISSUE THREAD

**Issue by haikyuu** [edgedb/edgedb#650]
First, congratulations on such a fantastic technology, and good luck with the rest.

I'm trying edgedb in docker, but can't run graphiql interface although i used the instruction of the tutorial.

Here is the log from the server `root: started port for config: Port(port=8888, protocol='graphql+http', database='tutorial', concurrency=4, user='http', 
address=frozenset({'0.0.0.0'}))`

But when i visit `127.0.0.1/explore`, it refuses to connect

![image](https://user-images.githubusercontent.com/8558836/57512566-81b52180-72fb-11e9-94db-09aaa6bf12c2.png)

That's the piece i was most excited to try. Do you know how i can solve it.

Here is how i ran the server 
```
docker run -it --rm -p 5655:5656 \
            -v datadir:/var/lib/edgedb/data \
            --name=edgedb-server edgedb/edgedb
```
I tried with different ports, but it didn't work either

**Comment by elprans** [comment]
You need to make sure you also expose the GraphQL port: `-p 8888:8888`

**Comment by haikyuu** [comment]
Thank you @elprans 
It Worked

**Comment by luca83** [comment]
hi guys.. I've the same problem .. below my configuration:

```
version: '3.7'
services:
        db:
                image: edgedb/edgedb
                volumes:
                 - db-data:/var/lib/edgedb/data
                ports:
                 - "5656:5656"
                 - "8888:8888"
                 - "8889:8889"
volumes:
        db-data:
```

any ideas?
