### ISSUE TITLE
Question on "Running EdgeDB shell in a linked container"

### ISSUE THREAD

**Issue by khaledez** [edgedb/edgedb#656]
Why the [documentation](https://edgedb.com/docs/admin/installation/#docker) suggests to run EdgeDB shell in a linked container? why not running it in the same container using exec?

Like this:
```bash
docker run -it --rm -p 5656:5656 -p 8888:8888 \
            -p 8889:8889 --name=edgedb-server \
            -v <datadir>:/var/lib/edgedb/data \
            edgedb/edgedb

docker exec -it edgedb-server edgedb -u edgedb
```

And just an addition, I like to use `docker-compose`, here is an example `docker-compose,yml` that runs the same as the above command:
```yml
version: '3.7'

services:
  db:
    image: edgedb/edgedb
    volumes:
      - db-data:/var/lib/edgedb/data
    ports:
      - "5656:5656"
      - "8888:8888"
      - "8889:8889"
  
volumes:
  db-data:
```

To run the server and the shell:
```bash
$ docker-compose up -d
$ docker-compose exec db edgedb -u edgedb 
```

`docker-compose` command is too long for me, that's why I have these two aliases:
```bash
alias dc="docker-compose"
alias dcup="docker-compose up -d"
```
